server {
    listen 80;
    listen [::]:80;
    server_name demo-203-116-30-130.sslip.io;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
